What metrics do we need exactly? Brainstorming
- EBITDA
- FFO
- FCF
- CFO
- Debt
- Debt/EBITDA
- Net Debt/EBITDA
- EBITDA / Interest Expense
- EBIT / Interest Expense
- Cash + Committed Credit Lines
- Short-term Debt

Include the data from at least the last 3 years, since it is is usually the time that comanies use in the financial reports.

In [18]:
import pandas as pd
import yfinance as yf

In [ ]:

ticker = "MSFT"
msft = yf.Ticker(ticker)

# 1. Download balance sheet, income statement, and cash flow
balance_sheet = msft.balance_sheet
income_statement = msft.financials
cashflow = msft.cashflow

From the balance sheet we can obtain many relevant metrics (Check the index).

In [8]:
balance_sheet#.index

,2025-06-30,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Ordinary Shares Number,7434000000.0,7434138859.0,7432000000.0,7464000000.0,NaN
Share Issued,7434000000.0,7434138859.0,7432000000.0,7464000000.0,NaN
Net Debt,12909000000.0,33315000000.0,12533000000.0,35850000000.0,NaN
Total Debt,60588000000.0,67127000000.0,59965000000.0,61270000000.0,NaN
Tangible Book Value,201366000000.0,121660000000.0,128971000000.0,87720000000.0,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,94555000000.0,75531000000.0,111256000000.0,104749000000.0,NaN
Other Short Term Investments,64313000000.0,57216000000.0,76552000000.0,90818000000.0,NaN
Cash And Cash Equivalents,30242000000.0,18315000000.0,34704000000.0,13931000000.0,NaN
Cash Equivalents,18531000000.0,6744000000.0,26226000000.0,5673000000.0,NaN
Cash Financial,11711000000.0,11571000000.0,8478000000.0,8258000000.0,NaN

In [15]:
balance_sheet.loc["Total Debt"].get("2025-06-30", 0)

60588000000.0

From here we can at least obtain the value for the EBITDA, which is one of the most relevant metrics.

In [9]:
income_statement

,2025-06-30,2024-06-30,2023-06-30,2022-06-30
Tax Effect Of Unusual Items,-77217840.76294,-100089983.022071,-2850000.0,43754000.0
Tax Rate For Calcs,0.176296,0.182313,0.19,0.131
Normalized EBITDA,160603000000.0,133558000000.0,105155000000.0,99905000000.0
Total Unusual Items,-438000000.0,-549000000.0,-15000000.0,334000000.0
Total Unusual Items Excluding Goodwill,-438000000.0,-549000000.0,-15000000.0,334000000.0
Net Income From Continuing Operation Net Minority Interest,101832000000.0,88136000000.0,72361000000.0,72738000000.0
Reconciled Depreciation,34153000000.0,22287000000.0,13861000000.0,14460000000.0
Reconciled Cost Of Revenue,87831000000.0,74114000000.0,65863000000.0,62650000000.0
EBITDA,160165000000.0,133009000000.0,105140000000.0,100239000000.0
EBIT,126012000000.0,110722000000.0,91279000000.0,85779000000.0
Net Interest Income,262000000.0,222000000.0,1026000000.0,31000000.0
Interest Expense,2385000000.0,2935000000.0,1968000000.0,2063000000.0
Interest Income,2647000000.0,3157000000.0,2994000000.0,2094000000.0
Normalized Income,102192782159.237061,88584910016.977936,72373150000.0,72447754000.0
Net Income From Continuing And Discontinued Operation,101832000000.0,88136000000.0,72361000000.0,72738000000.0
Total Expenses,153196000000.0,135689000000.0,123392000000.0,114887000000.0
Total Operating Income As Reported,128528000000.0,109433000000.0,88523000000.0,83383000000.0
Diluted Average Shares,7465000000.0,7469000000.0,7472000000.0,7540000000.0
Basic Average Shares,7433000000.0,7431000000.0,7446000000.0,7496000000.0
Diluted EPS,13.64,11.8,9.68,9.65
Basic EPS,13.7,11.86,9.72,9.7
Diluted NI Availto Com Stockholders,101832000000.0,88136000000.0,72361000000.0,72738000000.0
Net Income Common Stockholders,101832000000.0,88136000000.0,72361000000.0,72738000000.0
Net Income,101832000000.0,88136000000.0,72361000000.0,72738000000.0
Net Income Including Noncontrolling Interests,101832000000.0,88136000000.0,72361000000.0,72738000000.0
Net Income Continuous Operations,101832000000.0,88136000000.0,72361000000.0,72738000000.0
Tax Provision,21795000000.0,19651000000.0,16950000000.0,10978000000.0
Pretax Income,123627000000.0,107787000000.0,89311000000.0,83716000000.0
Other Income Expense,-5163000000.0,-1868000000.0,-238000000.0,302000000.0
Other Non Operating Income Expenses,-4725000000.0,-1319000000.0,-223000000.0,-32000000.0
Special Income Charges,-943000000.0,-206000000.0,-30000000.0,-101000000.0
Write Off,943000000.0,206000000.0,30000000.0,101000000.0
Gain On Sale Of Security,505000000.0,-343000000.0,15000000.0,435000000.0
Net Non Operating Interest Income Expense,262000000.0,222000000.0,1026000000.0,31000000.0
Interest Expense Non Operating,2385000000.0,2935000000.0,1968000000.0,2063000000.0
Interest Income Non Operating,2647000000.0,3157000000.0,2994000000.0,2094000000.0
Operating Income,128528000000.0,109433000000.0,88523000000.0,83383000000.0
Operating Expense,65365000000.0,61575000000.0,57529000000.0,52237000000.0
Research And Development,32488000000.0,29510000000.0,27195000000.0,24512000000.0
Selling General And Administration,32877000000.0,32065000000.0,30334000000.0,27725000000.0
Selling And Marketing Expense,25654000000.0,24456000000.0,22759000000.0,21825000000.0
General And Administrative Expense,7223000000.0,7609000000.0,7575000000.0,5900000000.0
Other Gand A,7223000000.0,7609000000.0,7575000000.0,5900000000.0
Gross Profit,193893000000.0,171008000000.0,146052000000.0,135620000000.0
Cost Of Revenue,87831000000.0,74114000000.0,65863000000.0,62650000000.0
Total Revenue,281724000000.0,245122000000.0,211915000000.0,198270000000.0
Operating Revenue,281724000000.0,245122000000.0,211915000000.0,198270000000.0

Finally here we have access to the FCF and other cash flow metrics.

In [10]:
cashflow

,2025-06-30,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Free Cash Flow,71611000000.0,74071000000.0,59475000000.0,65149000000.0,NaN
Repurchase Of Capital Stock,-18420000000.0,-17254000000.0,-22245000000.0,-32696000000.0,NaN
Repayment Of Debt,-3216000000.0,-29070000000.0,-2750000000.0,-9023000000.0,NaN
Issuance Of Debt,0.0,24395000000.0,0.0,0.0,NaN
Issuance Of Capital Stock,2056000000.0,2002000000.0,1866000000.0,1841000000.0,NaN
Capital Expenditure,-64551000000.0,-44477000000.0,-28107000000.0,-23886000000.0,NaN
End Cash Position,30242000000.0,18315000000.0,34704000000.0,13931000000.0,NaN
Beginning Cash Position,18315000000.0,34704000000.0,13931000000.0,14224000000.0,NaN
Effect Of Exchange Rate Changes,63000000.0,-210000000.0,-194000000.0,-141000000.0,NaN
Changes In Cash,11864000000.0,-16179000000.0,20967000000.0,-152000000.0,NaN
Financing Cash Flow,-51699000000.0,-37757000000.0,-43935000000.0,-58876000000.0,NaN
Cash Flow From Continuing Financing Activities,-51699000000.0,-37757000000.0,-43935000000.0,-58876000000.0,NaN
Net Other Financing Charges,-2291000000.0,-1309000000.0,-1006000000.0,-863000000.0,NaN
Cash Dividends Paid,-24082000000.0,-21771000000.0,-19800000000.0,-18135000000.0,NaN
Common Stock Dividend Paid,-24082000000.0,-21771000000.0,-19800000000.0,-18135000000.0,NaN
Net Common Stock Issuance,-16364000000.0,-15252000000.0,-20379000000.0,-30855000000.0,NaN
Common Stock Payments,-18420000000.0,-17254000000.0,-22245000000.0,-32696000000.0,NaN
Common Stock Issuance,2056000000.0,2002000000.0,1866000000.0,1841000000.0,NaN
Net Issuance Payments Of Debt,-8962000000.0,575000000.0,-2750000000.0,-9023000000.0,NaN
Net Short Term Debt Issuance,-5746000000.0,5250000000.0,0.0,0.0,NaN
Short Term Debt Issuance,NaN,5250000000.0,0.0,0.0,NaN
Net Long Term Debt Issuance,-3216000000.0,-4675000000.0,-2750000000.0,-9023000000.0,NaN
Long Term Debt Payments,-3216000000.0,-29070000000.0,-2750000000.0,-9023000000.0,NaN
Long Term Debt Issuance,0.0,24395000000.0,0.0,0.0,NaN
Investing Cash Flow,-72599000000.0,-96970000000.0,-22680000000.0,-30311000000.0,NaN
Cash Flow From Continuing Investing Activities,-72599000000.0,-96970000000.0,-22680000000.0,-30311000000.0,NaN
Net Other Investing Changes,2317000000.0,-1298000000.0,-3116000000.0,-2825000000.0,NaN
Net Investment Purchase And Sale,-4387000000.0,17937000000.0,10213000000.0,18438000000.0,NaN
Sale Of Investment,25388000000.0,35669000000.0,47864000000.0,44894000000.0,NaN
Purchase Of Investment,-29775000000.0,-17732000000.0,-37651000000.0,-26456000000.0,NaN
Net Business Purchase And Sale,-5978000000.0,-69132000000.0,-1670000000.0,-22038000000.0,NaN
Purchase Of Business,-5978000000.0,-69132000000.0,-1670000000.0,-22038000000.0,NaN
Net PPE Purchase And Sale,-64551000000.0,-44477000000.0,-28107000000.0,-23886000000.0,NaN
Purchase Of PPE,-64551000000.0,-44477000000.0,-28107000000.0,-23886000000.0,NaN
Operating Cash Flow,136162000000.0,118548000000.0,87582000000.0,89035000000.0,NaN
Cash Flow From Continuing Operating Activities,136162000000.0,118548000000.0,87582000000.0,89035000000.0,NaN
Change In Working Capital,-5350000000.0,1824000000.0,-2388000000.0,446000000.0,NaN
Change In Other Working Capital,5400000000.0,7035000000.0,5177000000.0,5805000000.0,NaN
Change In Other Current Liabilities,4947000000.0,5616000000.0,2825000000.0,3169000000.0,NaN
Change In Other Current Assets,-5994000000.0,-8465000000.0,-4824000000.0,-3514000000.0,NaN
Change In Payables And Accrued Expense,569000000.0,3545000000.0,-2721000000.0,2943000000.0,NaN
Change In Payable,569000000.0,3545000000.0,-2721000000.0,2943000000.0,NaN
Change In Account Payable,569000000.0,3545000000.0,-2721000000.0,2943000000.0,NaN
Change In Tax Payable,NaN,1687000000.0,-358000000.0,696000000.0,-2309000000.0
Change In Income Tax Payable,NaN,1687000000.0,-358000000.0,696000000.0,-2309000000.0
Change In Inventory,309000000.0,1284000000.0,1242000000.0,-1123000000.0,NaN
Change In Receivables,-10581000000.0,-7191000000.0,-4087000000.0,-6834000000.0,NaN
Changes In Account Receivables,-10581000000.0,-7191000000.0,-4087000000.0,-6834000000.0,NaN
Stock Based Compensation,11974000000.0,10734000000.0,9611000000.0,7502000000.0,NaN
Unrealized Gain Loss On Investment Securities,-536000000.0,-146000000.0,-303000000.0,-509000000.0,NaN
Asset Impairment Charge,943000000.0,206000000.0,30000000.0,101000000.0,NaN
Deferred Tax,-7056000000.0,-4738000000.0,-6059000000.0,-5702000000.0,NaN
Deferred Income Tax,-7056000000.0,-4738000000.0,-6059000000.0,-5702000000.0,NaN
Depreciation Amortization Depletion,34153000000.0,22287000000.0,13861000000.0,14460000000.0,NaN
Depreciation And Amortization,34153000000.0,22287000000.0,13861000000.0,14460000000.0,NaN
Depreciation,34153000000.0,22287000000.0,13861000000.0,14460000000.0,NaN
Operating Gains Losses,202000000.0,245000000.0,469000000.0,-1000000.0,NaN
Gain Loss On Investment Securities,202000000.0,245000000.0,469000000.0,-1000000.0,NaN
Net Income From Continuing Operations,101832000000.0,88136000000.0,72361000000.0,72738000000.0,NaN

So we see there is plenty of available data from the companies performance and it is more than enough to carry out a meaningful risk report. But in order to make things easier for the LLM we should probably focus in the most relevant.

In [13]:
print("cashflow metrics",cashflow.index)
print("income metrics",income_statement.index)
print("balance sheet metrics",balance_sheet.index)

cashflow metrics Index(['Free Cash Flow', 'Repurchase Of Capital Stock', 'Repayment Of Debt',
       'Issuance Of Debt', 'Issuance Of Capital Stock', 'Capital Expenditure',
       'End Cash Position', 'Beginning Cash Position',
       'Effect Of Exchange Rate Changes', 'Changes In Cash',
       'Financing Cash Flow', 'Cash Flow From Continuing Financing Activities',
       'Net Other Financing Charges', 'Cash Dividends Paid',
       'Common Stock Dividend Paid', 'Net Common Stock Issuance',
       'Common Stock Payments', 'Common Stock Issuance',
       'Net Issuance Payments Of Debt', 'Net Short Term Debt Issuance',
       'Short Term Debt Issuance', 'Net Long Term Debt Issuance',
       'Long Term Debt Payments', 'Long Term Debt Issuance',
       'Investing Cash Flow', 'Cash Flow From Continuing Investing Activities',
       'Net Other Investing Changes', 'Net Investment Purchase And Sale',
       'Sale Of Investment', 'Purchase Of Investment',
       'Net Business Purchase And Sale', 'Purchase Of Business',
       'Net PPE Purchase And Sale', 'Purchase Of PPE', 'Operating Cash Flow',
       'Cash Flow From Continuing Operating Activities',
       'Change In Working Capital', 'Change In Other Working Capital',
       'Change In Other Current Liabilities', 'Change In Other Current Assets',
       'Change In Payables And Accrued Expense', 'Change In Payable',
       'Change In Account Payable', 'Change In Tax Payable',
       'Change In Income Tax Payable', 'Change In Inventory',
       'Change In Receivables', 'Changes In Account Receivables',
       'Stock Based Compensation',
       'Unrealized Gain Loss On Investment Securities',
       'Asset Impairment Charge', 'Deferred Tax', 'Deferred Income Tax',
       'Depreciation Amortization Depletion', 'Depreciation And Amortization',
       'Depreciation', 'Operating Gains Losses',
       'Gain Loss On Investment Securities',
       'Net Income From Continuing Operations'],
      dtype='object')
income metrics Index(['Tax Effect Of Unusual Items', 'Tax Rate For Calcs',
       'Normalized EBITDA', 'Total Unusual Items',
       'Total Unusual Items Excluding Goodwill',
       'Net Income From Continuing Operation Net Minority Interest',
       'Reconciled Depreciation', 'Reconciled Cost Of Revenue', 'EBITDA',
       'EBIT', 'Net Interest Income', 'Interest Expense', 'Interest Income',
       'Normalized Income',
       'Net Income From Continuing And Discontinued Operation',
       'Total Expenses', 'Total Operating Income As Reported',
       'Diluted Average Shares', 'Basic Average Shares', 'Diluted EPS',
       'Basic EPS', 'Diluted NI Availto Com Stockholders',
       'Net Income Common Stockholders', 'Net Income',
       'Net Income Including Noncontrolling Interests',
       'Net Income Continuous Operations', 'Tax Provision', 'Pretax Income',
       'Other Income Expense', 'Other Non Operating Income Expenses',
       'Special Income Charges', 'Write Off', 'Gain On Sale Of Security',
       'Net Non Operating Interest Income Expense',
       'Interest Expense Non Operating', 'Interest Income Non Operating',
       'Operating Income', 'Operating Expense', 'Research And Development',
       'Selling General And Administration', 'Selling And Marketing Expense',
       'General And Administrative Expense', 'Other Gand A', 'Gross Profit',
       'Cost Of Revenue', 'Total Revenue', 'Operating Revenue'],
      dtype='object')
balance sheet metrics Index(['Ordinary Shares Number', 'Share Issued', 'Net Debt', 'Total Debt',
       'Tangible Book Value', 'Invested Capital', 'Working Capital',
       'Net Tangible Assets', 'Capital Lease Obligations',
       'Common Stock Equity', 'Total Capitalization',
       'Total Equity Gross Minority Interest', 'Stockholders Equity',
       'Gains Losses Not Affecting Retained Earnings',
       'Other Equity Adjustments', 'Retained Earnings', 'Capital Stock',
       'Common Stock', 'Total Liabilities Net Minority Interest',
       'Total Non Current Liabilities Net Minority Interest',
       'Other Non Current Liabilities', 'Tradeand Other Payables Non Current',
       'Non Current Deferred Liabilities', 'Non Current Deferred Revenue',
       'Non Current Deferred Taxes Liabilities',
       'Long Term Debt And Capital Lease Obligation',
       'Long Term Capital Lease Obligation', 'Long Term Debt',
       'Current Liabilities', 'Other Current Liabilities',
       'Current Deferred Liabilities', 'Current Deferred Revenue',
       'Current Debt And Capital Lease Obligation', 'Current Debt',
       'Other Current Borrowings', 'Commercial Paper',
       'Pensionand Other Post Retirement Benefit Plans Current',
       'Payables And Accrued Expenses', 'Payables', 'Total Tax Payable',
       'Income Tax Payable', 'Accounts Payable', 'Total Assets',
       'Total Non Current Assets', 'Other Non Current Assets',
       'Financial Assets', 'Investments And Advances',
       'Investmentin Financial Assets', 'Available For Sale Securities',
       'Long Term Equity Investment', 'Goodwill And Other Intangible Assets',
       'Other Intangible Assets', 'Goodwill', 'Net PPE',
       'Accumulated Depreciation', 'Gross PPE', 'Leases', 'Other Properties',
       'Machinery Furniture Equipment', 'Buildings And Improvements',
       'Land And Improvements', 'Properties', 'Current Assets',
       'Other Current Assets', 'Hedging Assets Current', 'Inventory',
       'Finished Goods', 'Work In Process', 'Raw Materials', 'Receivables',
       'Accounts Receivable', 'Allowance For Doubtful Accounts Receivable',
       'Gross Accounts Receivable',
       'Cash Cash Equivalents And Short Term Investments',
       'Other Short Term Investments', 'Cash And Cash Equivalents',
       'Cash Equivalents', 'Cash Financial'],
      dtype='object')

This may be the most important metrics:

### Leverage
- Debt / EBITDA
- Net Debt / EBITDA
- FFO Leverage (Debt ÷ FFO)

### Coverage
- EBITDA / Interest Expense
- EBIT / Interest Expense
- FFO / Interest Expense

### Cash Generation
- EBITDA (operating profitability proxy)
- FFO (after interest & tax, before working capital)
- CFO (after working capital changes)
- FCF (CFO – CapEx – dividends if relevant)
- CapEx (reinvestment pressure)

### Liquidity
- Cash + Committed Credit Lines ÷ Short-term Debt
- Cash ÷ Short-term Debt
- Current Debt ÷ Total Debt (refinancing pressure indicator)

### Risk Flags
- Debt maturity profile (near-term vs long-term structure)
- Stress testing: coverage under +200bps interest cost
- EBITDA → CFO → FCF conversion efficiency
- Goodwill & Intangibles share of assets (potential impairment risk if large)

In [ ]:
# final function
def get_fitch_metrics_timeseries(ticker_symbol, years=3):
    ticker = yf.Ticker(ticker_symbol)

    bs = ticker.balance_sheet      # Balance Sheet
    cf = ticker.cashflow           # Cash Flow
    is_ = ticker.financials        # Income Statement

    cols = bs.columns[:years]

    rows = []

    for col in cols:
        total_debt = bs.loc["Total Debt", col] if "Total Debt" in bs.index else 0
        cash = bs.loc["Cash", col] if "Cash" in bs.index else 0
        st_debt = bs.loc["Current Debt", col] if "Current Debt" in bs.index else 0
        lt_debt = bs.loc["Long Term Debt", col] if "Long Term Debt" in bs.index else 0

        ebit = is_.loc["EBIT", col] if "EBIT" in is_.index else 0
        ebitda = is_.loc["EBITDA", col] if "EBITDA" in is_.index else 0
        interest_exp = is_.loc["Interest Expense", col] if "Interest Expense" in is_.index else 0

        cfo = cf.loc["Total Cash From Operating Activities", col] if "Total Cash From Operating Activities" in cf.index else 0
        capex = cf.loc["Capital Expenditures", col] if "Capital Expenditures" in cf.index else 0
        fcf = cf.loc["Free Cash Flow", col] if "Free Cash Flow" in cf.index else 0

        net_debt = bs.loc["Net Debt", col] if "Net Debt" in bs.index else 0

        row = {
            "Period": col.strftime("%Y-%m-%d") if hasattr(col, "strftime") else str(col),
            "EBITDA": ebitda,
            "EBIT": ebit,
            "CFO": cfo,
            "CapEx": capex,
            "FCF": fcf,

            "Total Debt": total_debt,
            "Cash": cash,
            "Net Debt": net_debt,
            "Short-term Debt": st_debt,
            "Long-term Debt": lt_debt,

            # Leverage
            "Debt/EBITDA": (total_debt / ebitda) if ebitda else None,
            "Net Debt/EBITDA": (net_debt / ebitda) if ebitda else None,

            # Coverage
            "EBITDA/Interest": (ebitda / abs(interest_exp)) if interest_exp else None,
            "EBIT/Interest": (ebit / abs(interest_exp)) if interest_exp else None,

            # Liquidity
            "Cash/ST Debt": (cash / st_debt) if (cash and st_debt) else None,
            "ST Debt % Total Debt": (st_debt / total_debt) if (st_debt and total_debt) else None,
        }
        rows.append(row)

    return pd.DataFrame(rows).set_index("Period")


df = get_fitch_metrics_timeseries("MSFT", years=3)
print(df.to_markdown())

| Period     |      EBITDA |        EBIT |   CFO |   CapEx |        FCF |   Total Debt |   Cash |   Net Debt |   Short-term Debt |   Long-term Debt |   Debt/EBITDA |   Net Debt/EBITDA |   EBITDA/Interest |   EBIT/Interest | Cash/ST Debt   |   ST Debt % Total Debt |
|:-----------|------------:|------------:|------:|--------:|-----------:|-------------:|-------:|-----------:|------------------:|-----------------:|--------------:|------------------:|------------------:|----------------:|:---------------|-----------------------:|
| 2025-06-30 | 1.60165e+11 | 1.26012e+11 |     0 |       0 | 7.1611e+10 |   6.0588e+10 |      0 | 1.2909e+10 |         2.999e+09 |       4.0152e+10 |      0.378285 |         0.0805981 |           67.1551 |         52.8352 |                |              0.0494983 |
| 2024-06-30 | 1.33009e+11 | 1.10722e+11 |     0 |       0 | 7.4071e+10 |   6.7127e+10 |      0 | 3.3315e+10 |         8.942e+09 |       4.2688e+10 |      0.50468  |         0.250472  |           45.3182 |         37.7247 |                |              0.13321   |
| 2023-06-30 | 1.0514e+11  | 9.1279e+10  |     0 |       0 | 5.9475e+10 |   5.9965e+10 |      0 | 1.2533e+10 |         5.247e+09 |       4.199e+10  |      0.570335 |         0.119203  |           53.4248 |         46.3816 |                |              0.087501  |